### ISSUE TITLE
Contributor documentation for code generation

### ISSUE THREAD

**Issue by Aegonek** [WittleWolfie/WW-Blueprint-Core#25] opened 2022-01-06 11:38 UTC
Large amount of code in Blueprint Core is autogenerated. What is the workflow for editing existing, say, ActionBuilder? Should we update the code in BlueprintCoreGen/Templates? Or should we update the code directly in BlueprintCore?
Will the code generation step overwrite changes in BlueprintCore project, merge them or something different?
Could you give us the rough outline of how code generation works? I am a bit confused by the code.

I think it would be nice to answer this sort of questions in contributors guide.

**Comment by WittleWolfie** [comment] 2022-01-06 17:52
In main every BlueprintConfigurator, ActionsBuilder, and ConditionsBuilder class is auto-generated so all changes to those should go into BlueprintCoreGen.

Everything else you can update in BlueprintCore directly. Agreed documentation should clarify, but I'm going to wait until I finish my current refactoring to update.

**Comment by WittleWolfie** [comment] 2022-05-15 22:39
Closing as duplicate of [Issue 41](https://github.com/WittleWolfie/WW-Blueprint-Core/issues/41)

**Closed** 2022-05-15 22:38 UTC
